<a href="https://colab.research.google.com/github/Martigol2/lab-neural-networks/blob/master/challenge_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](tttboard.jpg)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [232]:
from tensorflow import keras
import numpy as np
import random

In [233]:
ttt = pd.read_csv('/content/tic-tac-toe.csv')
ttt.head()

  TL TM TR ML MM MR BL BM BR  class
0  x  x  x  x  o  o  x  o  o   True
1  x  x  x  x  o  o  o  x  o   True
2  x  x  x  x  o  o  o  o  x   True
3  x  x  x  x  o  o  o  b  b   True
4  x  x  x  x  o  o  b  o  b   True

In [234]:
ttt.shape

(958, 10)

In [235]:
ttt.describe()

         TL   TM   TR   ML   MM   MR   BL   BM   BR class
count   958  958  958  958  958  958  958  958  958   958
unique    3    3    3    3    3    3    3    3    3     2
top       x    x    x    x    x    x    x    x    x  True
freq    418  378  418  378  458  378  418  378  418   626

In [236]:
ttt.isnull().sum()

TL       0
TM       0
TR       0
ML       0
MM       0
MR       0
BL       0
BM       0
BR       0
class    0
dtype: int64

In [237]:
mapping = {
    'x': 1,
    'o': -1,
    'b': 0
}

ttt = ttt.replace(mapping)

ttt['class'] = ttt['class'].astype(int)

ttt.head()

/tmp/ipykernel_963/2279376896.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ttt = ttt.replace(mapping)

   TL  TM  TR  ML  MM  MR  BL  BM  BR  class
0   1   1   1   1  -1  -1   1  -1  -1      1
1   1   1   1   1  -1  -1  -1   1  -1      1
2   1   1   1   1  -1  -1  -1  -1   1      1
3   1   1   1   1  -1  -1  -1   0   0      1
4   1   1   1   1  -1  -1   0  -1   0      1

In [238]:
ttt.head()

   TL  TM  TR  ML  MM  MR  BL  BM  BR  class
0   1   1   1   1  -1  -1   1  -1  -1      1
1   1   1   1   1  -1  -1  -1   1  -1      1
2   1   1   1   1  -1  -1  -1  -1   1      1
3   1   1   1   1  -1  -1  -1   0   0      1
4   1   1   1   1  -1  -1   0  -1   0      1

## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

In [239]:
X = ttt.drop('class', axis=1) # all columns except class

y = ttt['class'] # class column

In [240]:
X.head()

   TL  TM  TR  ML  MM  MR  BL  BM  BR
0   1   1   1   1  -1  -1   1  -1  -1
1   1   1   1   1  -1  -1  -1   1  -1
2   1   1   1   1  -1  -1  -1  -1   1
3   1   1   1   1  -1  -1  -1   0   0
4   1   1   1   1  -1  -1   0  -1   0

In [241]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: class, dtype: int64

In [242]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42)

In [243]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

In [244]:
from tensorflow import keras

In [245]:
from keras.models import Sequential
from keras.layers import Dense

In [246]:
# create the model
input_shape=(9,)


model = Sequential()

model.add(Dense(32,
                activation='relu',
                input_shape=(9,)))

model.add(Dense(16,
                activation='relu'))

model.add(Dense(16,
                activation='relu'))

model.add(Dense(16,
                activation='relu'))

model.add(Dense(2,
                activation='softmax'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [247]:
#compile
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy'])

In [248]:
# train
history = model.fit(
    X_train,
    y_train,
    epochs=30,
    batch_size=32,
    validation_split=0.2
)

Epoch 1/30
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - accuracy: 0.6343 - loss: 0.6676 - val_accuracy: 0.6940 - val_loss: 0.6298
Epoch 2/30
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6343 - loss: 0.6491 - val_accuracy: 0.6940 - val_loss: 0.6123
Epoch 3/30
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6343 - loss: 0.6311 - val_accuracy: 0.6940 - val_loss: 0.5945
Epoch 4/30
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6343 - loss: 0.6120 - val_accuracy: 0.6940 - val_loss: 0.5786
Epoch 5/30
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6343 - loss: 0.5901 - val_accuracy: 0.6940 - val_loss: 0.5583
Epoch 6/30
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6362 - loss: 0.5640 - val_accuracy: 0.6940 - val_loss: 0.5384
Epoch 7/30
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6474 - loss: 0.5367 - val_accuracy: 0.7239 - val_loss: 0.5211
Epoch 8/30
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7090 - loss: 0.5047 - val_accuracy: 0.7463 - val_loss: 0.5017
Epoch 9/30
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7948 - loss: 0.4721 - val_accuracy: 0.8209 - val_loss: 0.4787
Epoch 10/30
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8451 - loss: 0.4377 - val_accuracy: 0.8731 - val_loss: 0.4453
Epoch 11/30
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8843 - loss: 0.3911 - val_accuracy: 0.8731 - val_loss: 0.4106
Epoch 12/30
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9011 - loss: 0.3386 - val_accuracy: 0.8955 - val_loss: 0.3695
Epoch 13/30
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9328 - loss: 0.2791 - val_accuracy: 0.9030 - val_loss: 0.3104
Epoch 14/30
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9515 - loss: 0.2142 - val_accuracy: 0.9328 - val_loss: 0.2625
Epoch 15/30
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9795 - loss: 0.1598 - val_accuracy: 0.9403 - val_loss: 0.2150
Epoch 16/30
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9888 - loss: 0.1131 - val_accuracy: 0.9478 - val_loss: 0.1865
Epoch 17/30
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9907 - loss: 0.0793 - val_accuracy: 0.9478 - val_loss: 0.1685
Epoch 18/30
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9925 - loss: 0.0624 - val_accuracy: 0.9478 - val_loss: 0.1586
Epoch 19/30
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9963 - loss: 0.0428 - val_accuracy: 0.9478 - val_loss: 0.1377
Epoch 20/30
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9981 - loss: 0.0325 - val_accuracy: 0.9627 - val_loss: 0.1508
Epoch 21/30
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0241 - val_accuracy: 0.9627 - val_loss: 0.1401
Epoch 22/30
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0185 - val_accuracy: 0.9627 - val_loss: 0.1352
Epoch 23/30
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0152 - val_accuracy: 0.9552 - val_loss: 0.1437
Epoch 24/30
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0123 - val_accuracy: 0.9701 - val_loss: 0.1365
Epoch 25/30
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0102 - val_accuracy: 0.9627 - val_loss: 0.1365
Epoch 26/30
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0086 - val_accuracy: 0.9701 - val_loss: 0.1362
Epoch 27/30
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.0075 - val_accuracy: 0.9701 - val_loss: 0.1366
Epoch 28/30
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0063 - val_accuracy: 0.9701 - val_loss: 0.1354
Epoch 29/30
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0056 - val_accuracy: 0.9701 - val_loss: 0.1366
Epoch 30/30
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0049 - val_accuracy: 0.9701 - val_loss: 0.1383

In [249]:
#evaluate the model
test_loss, test_accuracy = model.evaluate(
    X_test,
    y_test
)
train_loss, train_accuracy = model.evaluate(
    X_train,
    y_train
)

print(f"train accuracy {train_accuracy} and loss {train_loss}")
print(f"test accuracy {test_accuracy} and  loss {test_loss}")

9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9826 - loss: 0.0802
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9940 - loss: 0.0313
train accuracy 0.9940298795700073 and loss 0.03128597512841225
test accuracy 0.9826388955116272 and  loss 0.08023493736982346

In [250]:
model.save("tic-tac-toe.keras")

In [251]:
print(y.unique())

[1 0]

## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [252]:
# Load the saved model
loaded_model = keras.models.load_model('tic-tac-toe.keras')

# Select a few random indices from the test set
num_samples = 5
random_indices = random.sample(range(len(X_test)), num_samples)

sample_X_test = X_test.iloc[random_indices]
sample_y_test = y_test.iloc[random_indices]

# Make predictions
predictions = loaded_model.predict(sample_X_test)

# Convert predictions to binary (0 or 1)
predicted_classes = np.argmax(predictions, axis=1)

print("--- Sample Predictions ---")

for i in range(num_samples):
    print(
        f"Sample {i+1}: "
        f"Actual: {sample_y_test.iloc[i]}, "
        f"Predicted: {predicted_classes[i]}"
    )

WARNING:tensorflow:5 out of the last 5 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x7f19ed3f65c0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step
--- Sample Predictions ---
Sample 1: Actual: 1, Predicted: 1
Sample 2: Actual: 1, Predicted: 1
Sample 3: Actual: 1, Predicted: 1
Sample 4: Actual: 1, Predicted: 1
Sample 5: Actual: 1, Predicted: 1

## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

**Which approach(es) did you find helpful to improve your model performance?**

In [252]:
# first I set the epochs to 20 and I got and ok result then I change it to 30 and I got an improvement